---
# System images that are pre-pulled and pushed to local registry
n3000_opae_img: docker.io/starlingx/n3000-opae:stx.8.0-v1.0.2
kubernetes_entrypoint_img: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
calico_cni_img: quay.io/calico/cni:v3.24.0
calico_node_img: quay.io/calico/node:v3.24.0
calico_kube_controllers_img: quay.io/calico/kube-controllers:v3.24.0
multus_img: ghcr.io/k8snetworkplumbingwg/multus-cni:v3.9.2
sriov_cni_img: ghcr.io/k8snetworkplumbingwg/sriov-cni:v2.6.3
sriov_network_device_img: ghcr.io/k8snetworkplumbingwg/sriov-network-device-plugin:v3.5.1
# Nginx images
nginx_ingress_controller_img: registry.k8s.io/ingress-nginx/controller:v1.9.3
nginx_kube_webhook_certgen_img: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20231011-8b53cabe0
nginx_opentelemetry_img: registry.k8s.io/ingress-nginx/opentelemetry:v20230721-3e2062ee5
default_backend_img: registry.k8s.io/defaultbackend-amd64:1.5
# Cert-manager images
cert_manager_acmesolver_img: quay.io/jetstack/cert-manager-acmesolver:v1.13.1
cert_manager_cainjector_img: quay.io/jetstack/cert-manager-cainjector:v1.13.1
cert_manager_controller_img: quay.io/jetstack/cert-manager-controller:v1.13.1
cert_manager_webhook_img: quay.io/jetstack/cert-manager-webhook:v1.13.1
cert_manager_ctl_img: quay.io/jetstack/cert-manager-ctl:v1.13.1
cert_manager_ctl_img_171: quay.io/jetstack/cert-manager-ctl:v1.7.1
cert_manager_acmesolver_img_171: quay.io/jetstack/cert-manager-acmesolver:v1.7.1
cert_manager_cainjector_img_171: quay.io/jetstack/cert-manager-cainjector:v1.7.1
cert_manager_controller_img_171: quay.io/jetstack/cert-manager-controller:v1.7.1
cert_manager_webhook_img_171: quay.io/jetstack/cert-manager-webhook:v1.7.1
# Keep the snapshot-controller image in sync with the one provided at:
# cluster/addons/volumesnapshots/volume-snapshot-controller/volume-snapshot-controller-deployment.yaml
# in the kubernetes github repo
snapshot_controller_img: quay.io/k8scsi/snapshot-controller:v2.0.0-rc2
pause_img: k8s.gcr.io/pause:3.4.1
flux_helm_controller_img: docker.io/fluxcd/helm-controller:v0.35.0
flux_source_controller_img: docker.io/fluxcd/source-controller:v1.0.1
