---
enroll_init_finalized: /var/lib/factory-install/state/enroll-init

use_defaults_from_user_provided_docker_registries: false

# Update this fact if default registries are expected to private registries
default_docker_registries:
  k8s.gcr.io:
    url: k8s.gcr.io
  gcr.io:
    url: gcr.io
  quay.io:
    url: quay.io
  docker.io:
    url: docker.io
  docker.elastic.co:
    url: docker.elastic.co
  ghcr.io:
    url: ghcr.io
  registry.k8s.io:
    url: registry.k8s.io
  icr.io:
    url: icr.io
